name: plataforma_compras
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  cached_network_image: ^3.3.1
  provider: ^6.1.1
  carousel_slider: ^4.2.1
  dio: ^5.4.0
  geocoding: ^2.1.1
  intl: ^0.19.0
  geolocator: ^11.0.0
  shared_preferences: ^2.2.2
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logoAppBar.png
    - assets/images/logoPantallaInicio.png
    - assets/images/logoPantallaInicioAmber.png
    - assets/images/logoPantallaInicioMax.png
    - assets/images/logoPantallaInicioUltraMax.png
    - assets/images/ECommerceOpenBasket.png
    - assets/images/ECommerceCartCloud.png
    - assets/images/bag_plus.png
    - assets/images/cart_fill_round.png
    - assets/images/00001.png
    - assets/images/00002.png
    - assets/images/profile.png
    - assets/images/shopping_cart.png
    - assets/images/search_left.png
    - assets/images/love.png
    - assets/images/leftArrow.png
    - assets/images/logoPlus.png
    - assets/images/logoMinus.png
    - assets/images/logoDelete.png
    - assets/images/logoDeleteKlein.png
    - assets/images/logoInfo.png
    - assets/images/logoInfoLittle.png
    - assets/images/emptyCart.png
    - assets/images/imageDialogBox.png
    - assets/images/weightMessage.png
    - assets/images/infoMessage.png
    - assets/images/logoCross.png
    - assets/images/logoQuestion.png
    - assets/images/addressMessage.png
    - assets/images/logoGetMyPlace.png
    - assets/images/logoPlace.png
    - assets/images/logoDelibery.png
    - assets/images/logoPhone.png
    - assets/images/logoPaymentMethod.png
    - assets/images/logoPaymentMethod1.png
    - assets/images/logoInformation.png
    - assets/images/logoHelp.png
    - assets/images/logoMyPurchases.png
    - assets/images/logoDirections.png
    - assets/images/logoPersonalData.png
    - assets/images/emptyAddress.png
    - assets/images/logoDefaultAddress.png
    - assets/images/logoExit.png
    - assets/images/logoStateTransition.png
    - assets/images/logoPlay.png
    - assets/images/logoComment.png
    - assets/images/logoWhatsapp.png
    - assets/images/logoUpCatalog.png
    - assets/images/logoNewProduct.png
    - assets/images/logoModifyProduct.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
